// This file is automatically generated.
// Please do not edit this file directly.
export interface Deal {
  address: string;
  timestamp: number;
  id: number,
  price: number;
  email: string;
  item: string;
  description: string;
  imageUrl: string;
}
